### ISSUE TITLE
Improve error message reporting when an exception causes the BitFunnel process to terminate

### ISSUE THREAD

**Issue by hausdorff** [BitFunnel/BitFunnel#258]
One of the pain points of debugging BitFunnel is the lack of error messages. A good example is #257, where parsing a malformatted chunk file causes us to throw a `FatalError` that contains the error message `"NullLogger::Abort()"`. The pain here comes from the fact that the real error is swallowed -- if you run out of memory (or any number of other things happens), you get the same error.

Errors like these have personally cost me hours of time, as they usually mean that I have to crack open GDB (or something) to figure out what the error really is.

It seems to me that there are a bunch of relatively simple things we could do that would help this situation:

* Log the message in a `FatalError` before re-throwing it to terminate the process.
* Use something like [`std::current_exception`](http://en.cppreference.com/w/cpp/error/current_exception) to convert non-BitFunnel errors (like those from the standard library), and convert them to `std::exception` so that we can log a `.why()` before re-throwing.

Thoughts? I think this is pretty easy to do and am happy to take point.

**Comment by MikeHopcroft** [comment]
This is actually on our radar. The original BitFunnel code from Bing makes heavy use of the `LogAbortB()` reporting mechanism that actually gathers useful information in the form of a text message and a call stack. We did not port the logging mechanism so at the moment we have a placeholder `NullLogger` and this is the reason for the thin error messages.

We decided not to support `LogAbortB()` moving forward and are replacing it gradually with the `CHECK_PRED()` macro which is defined in inc/LoggerInterfaces/Check.h. The `CHECK_PRED()` macros work more like the gtest `ASSERT_PRED()` macros. Here's an example usage:

~~~
                CHECK_LT(opcode, Opcode::Last)
                    << "Unknown opcode " << opcode;
~~~

At this point we're still evaluating our implementation of the `CHECK_PRED()` macros before replacing `LogAbortB()`. There is some evidence that our implementation of `CHECK_PRED()` may cause build breaks on some versions of GCC.

Once we sort out these build breaks, our plan is to go in and replace all of the `LogAbortB()` instances with `CHECK_PRED()`.

Since we are evaluating `CHECK_PRED()`, I am willing to replace a limited number of the most egregious uses of `LogAbortB()` as part of our evaluation process. Please feel free to submit a pull request using `CHECK_PRED()` in the most impactful places.

**Comment by MikeHopcroft** [comment]
The GCC issue I mention is #225. Please feel free to investigate. This issue is the reason we haven't yet moved away from LogAssertB().

**Comment by danluu** [comment]
One example of this is

~~~
#0  0x00007ffff7ae28bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004a9792 in BitFunnel::BlockAllocator::AllocateBlock() ()
#2  0x0000000000471b45 in BitFunnel::Slice::Slice(BitFunnel::Shard&) ()
#3  0x000000000046b679 in BitFunnel::Shard::CreateNewActiveSlice() ()
#4  0x000000000046b5bc in BitFunnel::Shard::AllocateDocument(unsigned long) ()
#5  0x0000000000480594 in BitFunnel::Ingestor::Add(unsigned long, BitFunnel::IDocument const&) ()
#6  0x0000000000483195 in BitFunnel::ChunkIngestor::OnDocumentExit(BitFunnel::IChunkWriter&, unsigned long) ()
#7  0x0000000000483cff in BitFunnel::ChunkReader::ProcessDocument() ()
#8  0x0000000000483b47 in BitFunnel::ChunkReader::ChunkReader(char const*, char const*, BitFunnel::IChunkProcessor&) ()
#9  0x000000000048350a in BitFunnel::ChunkManifestIngestor::IngestChunk(unsigned long) const ()
#10 0x0000000000485777 in BitFunnel::ChunkEnumerator::ChunkEnumerator(BitFunnel::IChunkManifestIngestor const&, unsigned long) ()
#11 0x0000000000485561 in BitFunnel::IngestChunks(BitFunnel::IChunkManifestIngestor const&, unsigned long) ()
#12 0x0000000000453481 in BitFunnel::StatisticsBuilder::LoadAndIngestChunkList(std::ostream&, char const*, char const*, int, bool, bool) const ()
#13 0x0000000000452a54 in BitFunnel::StatisticsBuilder::Main(std::istream&, std::ostream&, int, char const**) ()
#14 0x0000000000447fbe in BitFunnel::BitFunnelTool::Main(std::istream&, std::ostream&, int, char const**) ()
#15 0x0000000000447e6b in main ()
~~~

This fails with `Unexpected error.`
