### ISSUE TITLE
NativeCode.AndRowJzDelta0 segfault on clang and gcc release build

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#306]
This consistently fails for me with a clang release build and consistently passes with a clang debug build.

Here's the call stack for the failure from the release build:

~~~
Thread 1 "PlanTest" received signal SIGSEGV, Segmentation fault.
0x00000000004ac958 in BitFunnel::MatchTreeCompiler::Run(unsigned long, void* const*, unsigned long, long const*, BitFunnel::ResultsBuffer&) ()
(gdb) bt
#0  0x00000000004ac958 in BitFunnel::MatchTreeCompiler::Run(unsigned long, void* const*, unsigned long, long const*, BitFunnel::ResultsBuffer&) ()
#1  0x0000000000499ac9 in BitFunnel::NativeCodeVerifier::Verify(char const*) ()
#2  0x0000000000499fb5 in BitFunnel::NativeCode_AndRowJzDelta0_Test::TestBody() ()
#3  0x000000000050f2dd in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#4  0x00000000004f36c9 in testing::Test::Run() ()
#5  0x00000000004f4710 in testing::TestInfo::Run() ()
#6  0x00000000004f4e33 in testing::TestCase::Run() ()
#7  0x00000000004fda09 in testing::internal::UnitTestImpl::RunAllTests() ()
#8  0x000000000050fdaf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#9  0x00000000004fd510 in testing::UnitTest::Run() ()
#10 0x00000000005179d0 in main ()
~~~

Here's the assembly down to where the problem happens:

~~~
PlanTest`BitFunnel::MatchTreeCompiler::Run:
    0x100051360 <+0>:   pushq  %rbp
    0x100051361 <+1>:   movq   %rsp, %rbp
    0x100051364 <+4>:   pushq  %r15
    0x100051366 <+6>:   pushq  %r14
    0x100051368 <+8>:   pushq  %r13
    0x10005136a <+10>:  pushq  %r12
    0x10005136c <+12>:  pushq  %rbx
    0x10005136d <+13>:  subq   $0x248, %rsp              ; imm = 0x248 
    0x100051374 <+20>:  movq   %r9, %rbx
    0x100051377 <+23>:  movq   %r8, %r14
    0x10005137a <+26>:  movq   %rcx, %r15
    0x10005137d <+29>:  movq   %rdx, %r12
    0x100051380 <+32>:  movq   %rsi, %r13
    0x100051383 <+35>:  movq   %rdi, -0x270(%rbp)
    0x10005138a <+42>:  leaq   -0x268(%rbp), %rdi
    0x100051391 <+49>:  movl   $0x238, %esi              ; imm = 0x238 
    0x100051396 <+54>:  callq  0x1000b879a               ; symbol stub for: __bzero
    0x10005139b <+59>:  movq   %r13, -0x268(%rbp)
    0x1000513a2 <+66>:  movq   %r12, -0x260(%rbp)
    0x1000513a9 <+73>:  movq   %r15, -0x258(%rbp)
    0x1000513b0 <+80>:  movq   %r14, -0x250(%rbp)
    0x1000513b7 <+87>:  movq   $0x0, -0x248(%rbp)
    0x1000513c2 <+98>:  movq   0x8(%rbx), %rax
    0x1000513c6 <+102>: movq   %rax, -0x40(%rbp)
    0x1000513ca <+106>: movq   $0x0, -0x38(%rbp)
    0x1000513d2 <+114>: movq   0x18(%rbx), %rax
    0x1000513d6 <+118>: movq   %rax, -0x30(%rbp)
    0x1000513da <+122>: leaq   -0x268(%rbp), %rdi
    0x1000513e1 <+129>: movq   -0x270(%rbp), %rax
    0x1000513e8 <+136>: callq  *0x88(%rax)
    0x1000513ee <+142>: movq   -0x38(%rbp), %rax
    0x1000513f2 <+146>: movq   %rax, 0x10(%rbx)
~~~

At `0x1000513f2`, `rbx` is 0, so we try to write to the bogus address `0x10`.

Before the `callq  *0x88(%rax)`, `rbx` is `140734799798608`, which is a plausible address.

The xcode debugger claims that function called at `0x1000513e8` is 

~~~
    0x1002d60d3: subq   $0x18, %rsp
    0x1002d60d7: movq   %rbp, (%rsp)
    0x1002d60db: leaq   0x18(%rsp), %rbp
    0x1002d60e0: movq   0x18(%rdi), %rsi
    0x1002d60e4: movq   (%rsi), %r8
    0x1002d60e7: movq   0x8(%rsi), %r9
    0x1002d60eb: movq   (%rdi), %rax
    0x1002d60ee: orq    %rax, %rax
    0x1002d60f1: je     0x1002d6206
    0x1002d60f7: movq   0x8(%rdi), %rdx
    0x1002d60fb: movq   (%rdx), %rdx
    0x1002d60fe: movq   0x10(%rdi), %rax
    0x1002d6102: shlq   $0x3, %rax
    0x1002d6106: addq   %rdx, %rax
    0x1002d6109: movq   %rax, -0x8(%rbp)
    0x1002d610d: movq   %rdx, %rcx
    0x1002d6110: cmpq   -0x8(%rbp), %rcx
    0x1002d6114: je     0x1002d61f3
    0x1002d611a: movq   (%rcx,%r8), %rbx
    0x1002d611e: orq    %rbx, %rbx
    0x1002d6121: je     0x1002d614d
    0x1002d6127: andq   (%rcx,%r9), %rbx
    0x1002d612b: je     0x1002d614d
    0x1002d6131: pushq  %rcx
    0x1002d6132: subq   %rdx, %rcx
    0x1002d6135: shrq   $0x3, %rcx
    0x1002d6139: movq   $0x1, %rax
    0x1002d6140: shlq   %cl, %rax
    0x1002d6143: orq    %rax, 0x20(%rdi)
    0x1002d6147: orq    %rbx, 0x28(%rdi,%rcx,8)
    0x1002d614c: popq   %rcx
    0x1002d614d: movq   0x20(%rdi), %rax
    0x1002d6151: orq    %rax, %rax
    0x1002d6154: je     0x1002d61ea
    0x1002d615a: pushq  %r9
    0x1002d615c: pushq  %r10
    0x1002d615e: pushq  %r11
    0x1002d6160: pushq  %r12
    0x1002d6162: pushq  %r13
    0x1002d6164: pushq  %r14
    0x1002d6166: pushq  %r15
    0x1002d6168: movq   0x238(%rdi), %r10
    0x1002d616f: movq   (%rdx), %r9
    0x1002d6172: movq   0x20(%rdi), %rax
    0x1002d6176: bsfq   %rax, %r15
    0x1002d617a: je     0x1002d61d8
    0x1002d6180: movq   0x28(%rdi,%r15,8), %r14
    0x1002d6185: bsfq   %r14, %r13
    0x1002d6189: je     0x1002d61ca
    0x1002d618f: movq   0x230(%rdi), %r12
    0x1002d6196: cmpq   0x228(%rdi), %r12
    0x1002d619d: je     0x1002d61c1
    0x1002d61a3: shlq   $0x4, %r12
    0x1002d61a7: movq   %r15, %r11
    0x1002d61aa: shlq   $0x6, %r11
    0x1002d61ae: addq   %r13, %r11
    0x1002d61b1: movq   %r9, (%r10,%r12)
    0x1002d61b5: movq   %r11, 0x8(%r10,%r12)
    0x1002d61ba: incq   0x230(%rdi)
    0x1002d61c1: btrq   %r13, %r14
    0x1002d61c5: jmp    0x1002d6185
    0x1002d61ca: movq   %r14, 0x28(%rdi,%r15,8)
    0x1002d61cf: btrq   %r15, %rax
    0x1002d61d3: jmp    0x1002d6176
    0x1002d61d8: movq   %rax, 0x20(%rdi)
    0x1002d61dc: popq   %r15
    0x1002d61de: popq   %r14
    0x1002d61e0: popq   %r13
    0x1002d61e2: popq   %r12
    0x1002d61e4: popq   %r11
    0x1002d61e6: popq   %r10
    0x1002d61e8: popq   %r9
    0x1002d61ea: addq   $0x8, %rcx
    0x1002d61ee: jmp    0x1002d6110
    0x1002d61f3: decq   (%rdi)
    0x1002d61f6: movq   $0x8, %rax
    0x1002d61fd: addq   %rax, 0x8(%rdi)
    0x1002d6201: jmp    0x1002d60eb
    0x1002d6206: movq   %r11, %rax
    0x1002d6209: movq   (%rsp), %rbp
    0x1002d620d: addq   $0x18, %rsp
    0x1002d6211: retq   
~~~

If I'm reading this correctly, this function appears to modify RBX (a callee-save register) without saving and restoring it. If I had to guess, I'd say that RBX is the accumulator and it eventually gets cleared to 0.

In `CallingConvention.h`, `NativeJIT` appears to consider `RBX` a callee-save register based on the comment. I haven't tried to compare the bit positions to make sure the indices are correct:

~~~
#ifdef NATIVEJIT_PLATFORM_WINDOWS
        // Register masks of volatile integer and floating point registers.
        // TODO: This could be replaced with constexpr: add operator| to Register and use it to define the masks.
        // Note: RIP is included in volatiles.
        static const unsigned c_rxxVolatileRegistersMask = 0xf07;     // 1 0000 1111 0000 0111 (RAX | RCX | RDX | R8 | R9 | R10 | R11 | RIP)
        static const unsigned c_xmmVolatileRegistersMask = 0x3f;      //   0000 0000 0011 1111 (XMM0-XMM5)

        // Register masks of non-volatile integer and floating point registers.
        // Note: RIP not included.
        static const unsigned c_rxxNonVolatileRegistersMask = 0xf0f8; // 0 1111 0000 1111 1000 (RBX | RSP | RBP | RSI | RDI | R12-R15)
        static const unsigned c_xmmNonVolatileRegistersMask = 0xffc0; //   1111 1111 1100 0000 (XMM6-XMM15)

        // Register masks of registers that can be written to.
        static const unsigned c_rxxWritableRegistersMask = 0xFFFF;    // Everything except RIP.
        static const unsigned c_xmmWritableRegistersMask = 0xFFFF;    // All XMM registers.
#else
        // Register masks of volatile integer and floating point registers.
        // TODO: This could be replaced with constexpr: add operator| to Register and use it to define the masks.
        // Note: RIP is included in volatiles.
        static const unsigned c_rxxVolatileRegistersMask = 0xfc7;     // 1 0000 1111 1100 0111 (RAX | RCX | RDX | RSI | RDI | R8 | R9 | R10 | R11 | RIP)
        static const unsigned c_xmmVolatileRegistersMask = 0xffff;    //   1111 1111 1111 1111 (XMM0-XMM15)

        // Register masks of non-volatile integer and floating point registers.
        // Note: RIP not included.
        static const unsigned c_rxxNonVolatileRegistersMask = 0xf038; // 0 1111 0000 0011 1000 (RBX | RSP | RBP | R12-R15)
        static const unsigned c_xmmNonVolatileRegistersMask = 0x0000; //   0000 0000 0000 0000 (none)

        // Register masks of registers that can be written to.
        static const unsigned c_rxxWritableRegistersMask = 0xFFFF;    // Everything except RIP.
        static const unsigned c_xmmWritableRegistersMask = 0xFFFF;    // All XMM registers.
#endif
~~~

I checked to make sure that we're not incorrectly defining `NATIVEJIT_PLATFORM_WINDOWS`, and that isn't the problem. I find it unlikely that our bit positions indices are wrong, which seems to indicate that we're somehow not saving a callee-saved register despite using it (or that I'm reading the function incorrectly).

Although this is another bug that appears in the release build and not in debug, this appears to be different from #298.

**Comment by MikeHopcroft** [comment]
Fixed by b6905d5b077a3cec515cefa38e4e75f1f35785f3
