### ISSUE TITLE
Crash when ingesting all of GOV2

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#387]
Since the MG4J -> chunk file code is new, I'm suspicious of that, but this could just as easily be in the BitFunnel ingestion code -- we've only tried a relatively narrow range of documents, so we could easily have a bug that's been hiding this whole time.

~~~
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) run
Starting program: /home/danluu/dev/BitFunnel/build-ninja/tools/BitFunnel/src/BitFunnel statistics -text /home/danluu/dev/bf-go
v2/manifest.txt /home/danluu/dev/bf-gov2/config
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd6f4f700 (LWP 11926)]
Creating shard: 0
Loading chunk list file '/home/danluu/dev/bf-gov2/manifest.txt'
Output dirextory: '/home/danluu/dev/bf-gov2/config'
Reading 1 files
Ingesting . . .

Thread 1 "BitFunnel" hit Catchpoint 1 (exception thrown), 0x00007ffff7ae28bd in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7ae28bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000048755e in BitFunnel::ChunkReader::ProcessStream() ()
#2  0x0000000000487178 in BitFunnel::ChunkReader::ProcessDocument() ()
#3  0x0000000000487007 in BitFunnel::ChunkReader::ChunkReader(char const*, char const*, BitFunnel::IChunkProcessor&) ()
#4  0x00000000004869ca in BitFunnel::ChunkManifestIngestor::IngestChunk(unsigned long) const ()
#5  0x0000000000488c37 in BitFunnel::ChunkEnumerator::ChunkEnumerator(BitFunnel::IChunkManifestIngestor const&, unsigned long$ ()
#6  0x0000000000488a21 in BitFunnel::IngestChunks(BitFunnel::IChunkManifestIngestor const&, unsigned long) ()
#7  0x0000000000453fe1 in BitFunnel::StatisticsBuilder::LoadAndIngestChunkList(std::ostream&, char const*, char const*, int, $ool, bool) const ()
#8  0x00000000004535b4 in BitFunnel::StatisticsBuilder::Main(std::istream&, std::ostream&, int, char const**) ()
#9  0x0000000000448a8e in BitFunnel::BitFunnelTool::Main(std::istream&, std::ostream&, int, char const**) ()
#10 0x000000000044893b in main ()
~~~

We throw because PeekChar tries to read past the end of the buffer.

This appears to happen on DocId 47352 (0xb8f8).

The end of that document appears to be 234876038 bytes into the chunk file? At that point, BitFunnel tries to open a new stream instead of closing the document.

**Comment by danluu** [comment]
It looks like the chunk file is malformed. It looks like the chunk file simply ends at that document, which is too low (the corpus should contain millions of documents). The document isn't terminated correctly -- the chunk appears to end mid-stream with no terminating characters other than the term terminator, i.e., there's a term followed by a single NULL byte and then the file ends.

**Comment by danluu** [comment]
I'm not sure what happened, but re-running after the latest changes allows us to run past this point. I'm three hours into generating a new chunk file and it's still going, so there may still be bugs, but if we get malformed output later that will probably be a different bug.

It's possible that we have some kind of non-deterministic failure here, but given the severity of bugs that we've had open for months, it's unlikely that we'll ever get around to debugging this unless we find that it's very disruptive, so I'm going to close this as "won't fix".
